cc_binary(
    name = "template_meta_programming",
    srcs = glob([
        "*.cpp",
        "*.h",
    ]),
)

cc_binary(
    name = "template",
    srcs = glob([
        "*.cpp",
        "*.h",
    ]),
)

cc_binary(
    name = "meta",
    srcs = glob([
        "*.cpp",
        "*.h",
    ]),
)

cc_binary(
    name = "programming",
    srcs = glob([
        "*.cpp",
        "*.h",
    ]),
)
